### ISSUE TITLE
Syntax Error In push_to_erpnext.py

### ISSUE THREAD

**Issue by ShariarMhaboob23** [frappe/push-biometric-erpnext#2]
It gives below syntax error in line 50

![Screenshot from 2019-12-03 14-03-47](https://user-images.githubusercontent.com/10448004/70033222-3769f980-15d9-11ea-81cb-ea3ac57c6476.png)

**Comment by karthikeyan5** [comment]
@ShariarMhaboob23, it turns out, the f-string syntax is not supported in Python 3.5 and below... can you please try in python 3.6+ ?... 

thanks for reporting it... I will add this detail in the readme.

**Comment by ShariarMhaboob23** [comment]
@karthikeyan5  , understand. I am using Python 3.5.2. Let me try it. Thank you very much.

**Comment by ShariarMhaboob23** [comment]
@karthikeyan5  , I have run the  **push_to_erpnext.py**  script successfully,erpnext  get the data in employee checkin. But it takes almost 30-40 minutes to sync new checkin data. Do I need to run the script every time in production? And can you also create the attendance at the same time?

**Comment by karthikeyan5** [comment]
@ShariarMhaboob23, you can adjust the `PULL_FREQUENCY` in the 'local_config.py' file to make it run more frequently.

which platform are you running this script on? To run the script regularly you have the following options:
For Linux:
- Option 1. You can set up a Cron job or something and call the main function using ` python -c 'from push_to_erpnext import main; print main()' `
- Option 2. You can setup this 'push_to_erpnext.py' as a service using Systemd. Please refer to this [link](https://tecadmin.net/setup-autorun-python-script-using-systemd/).

For Windows:
- Follow the second part of this repo's readme, after you have run the 'push_to_erpnext.py' atleast once(i.e. setup is complete), which you have already done.


Also, [auto attendance](https://erpnext.com/docs/user/manual/en/human-resources/auto-attendance) is attempting to mark attendance every hour. You can only reliably mark the attendance once the shift ends. Hence, when a shift ends, Auto Attendance gets to mark the attendance based on, the 'Employee Checkin' Records and up to the 'last_sync_of_checkin' time in the shift type document.

**Comment by karthikeyan5** [comment]
Let's take further discussions to https://discuss.erpnext.com ...

**Comment by ShariarMhaboob23** [comment]
Thank you @karthikeyan5  . Let me try and will continue the discussion in forum.
